auto_save: true
display_label_popup: true
store_data: true
keep_prev: false

flags: null
labels: null
file_search: null
sort_labels: true
validate_label: null

# main
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

epsilon: 11.0

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null

  open_next: [D, Ctrl+Shift+D]
  open_prev: [A, Ctrl+Shift+A]

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  add_point: Ctrl+Shift+P
  create_polygon: [N, Ctrl+N]
  create_rectangle: [R, Ctrl+R]
  create_circle: null
  create_line: null
  create_point: null
  create_linestrip: null
  edit_polygon: [J, Ctrl+J]
  delete_polygon: [T, Delete]
  duplicate_polygon: Ctrl+D
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, Backspace]
  edit_label: Ctrl+E
  edit_line_color: Ctrl+L
  edit_fill_color: Ctrl+Shift+L
  polygon_add_point: [W, Ctrl+P]
  polygon_del_point: E